Add all pgm level models
prio-data/views_pipeline pull request #156
Opened 2024-11-04 09:21 UTC by xiaolong0728

1. All pgm level models are added. Newly created ones use darts stepshifter.
2. One cm level model (brown cheese) finished with Borbala.
3. Update stepshifter darts to solve the problem that cm data have discrete time series (countries appear and disappear)
4. Update set_path logging level from INFO to DEBUG, but WARNING is kept.

2024-11-04 14:49 UTC, smellycloud requested changes
Overall everything works but there are missing dirs inside a few models. old_money, midnight_rain and invisible_string. Maybe more?

2024-11-04 14:49 UTC, smellycloud commented on common_utils/model_path.py
Check with the updated dev branch. I made changes to ModelPath and EnsemblePath. You should see _initialize_model_specific_directories() and _initialize_ensemble_specific_directories. Not sure if those changes reflect here. Maybe I'm missing something.

2024-11-04 14:49 UTC, smellycloud commented on common_utils/set_path.py
These logging levels make more sense

2024-11-04 14:49 UTC, smellycloud commented on models/.DS_Store
Should be deleted?

2024-11-04 14:49 UTC, smellycloud commented on common_utils/views_stepshifter_darts/stepshifter.py
```
    @staticmethod
    def _resolve_estimator(func_name: str):
        """ Lookup table for supported estimators.
        This is necessary because sklearn estimator default arguments
        must pass equality test, and instantiated sub-estimators are not equal. """
        funcs = {
            'LinearRegressionModel': LinearRegressionModel,
            'RandomForestModel': RandomForest,
            'LightGBMModel': LightGBMModel,
            'XGBModel': XGBModel,
        }
```

This bit here could be a switch case with the import statement in it as well? We are importing all models and saving them to a dict at runtime when I think we only need one. Not important though.

```
    @staticmethod
    def _resolve_estimator(func_name: str):
        """ Lookup table for supported estimators.
        This is necessary because sklearn estimator default arguments
        must pass equality test, and instantiated sub-estimators are not equal. """

        match func_name:
            case 'LinearRegressionModel':
                from darts.models import LinearRegressionModel
                return LinearRegressionModel
            case 'RandomForestModel':
                from darts.models import RandomForest
                return RandomForest
            case 'LightGBMModel':
                from darts.models import LightGBMModel
                return LightGBMModel
            case 'XGBModel':
                from darts.models import XGBModel
                return XGBModel
            case _:
                raise ValueError(f"Model {func_name} is not a valid Darts forecasting model or is not supported now. "
                                f"Change the model in the config file.")

```

Also it errors out when running old_money and caring_fish `python main.py --train`

```
Traceback (most recent call last):
  File "/Users/user/Desktop/views_pipeline/models/old_money/main.py", line 38, in <module>
    execute_single_run(args)
  File "/Users/user/Desktop/views_pipeline/models/old_money/src/management/execute_model_runs.py", line 43, in execute_single_run
    execute_model_tasks(config=config, project=project, train=args.train, eval=args.evaluate,
  File "/Users/user/Desktop/views_pipeline/models/old_money/src/management/execute_model_tasks.py", line 58, in execute_model_tasks
    train_model_artifact(config)
  File "/Users/user/Desktop/views_pipeline/models/old_money/src/training/train_model.py", line 19, in train_model_artifact
    stepshift_model = stepshift_training(config, run_type, df_viewser)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/views_pipeline/models/old_money/src/training/train_model.py", line 31, in stepshift_training
    stepshift_model = get_model(config, partitioner_dict)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/views_pipeline/models/old_money/src/utils/utils_run.py", line 13, in get_model
    model = HurdleModel(config, partitioner_dict)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/views_pipeline/common_utils/views_stepshifter_darts/hurdle_model.py", line 38, in __init__
    super().__init__(config, partitioner_dict)
  File "/Users/user/Desktop/views_pipeline/common_utils/views_stepshifter_darts/stepshifter.py", line 15, in __init__
    self._reg = self._resolve_estimator(config['model_reg'])
                                        ~~~~~~^^^^^^^^^^^^^
  File "/Users/user/miniforge3/envs/pipeline/lib/python3.11/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'model_reg'
2024-11-04 15:07:28,524 /Users/user/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [3926] [MainThread] - INFO - Cache file: /Users/user/Desktop/views_pipeline/.global_cache.pkl deleted at exit
```

2024-11-04 14:49 UTC, smellycloud commented on models/dark_paradise/main.py
Model runs when I run main.py --train but errors out at the end when saving the model file:

```
Traceback (most recent call last):
  File "/Users/user/Desktop/views_pipeline/models/dark_paradise/main.py", line 35, in <module>
    execute_single_run(args)
  File "/Users/user/Desktop/views_pipeline/models/dark_paradise/src/management/execute_model_runs.py", line 45, in execute_single_run
    execute_model_tasks(config=config, project=project, train=args.train, eval=args.evaluate,
  File "/Users/user/Desktop/views_pipeline/models/dark_paradise/src/management/execute_model_tasks.py", line 57, in execute_model_tasks
    train_model_artifact(config)
  File "/Users/user/Desktop/views_pipeline/models/dark_paradise/src/training/train_model.py", line 23, in train_model_artifact
    stepshift_model.save(path_artifacts / model_filename)
                         ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'
2024-11-04 15:33:07,115 /Users/user/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [5455] [MainThread] - INFO - Cache file: /Users/user/Desktop/views_pipeline/.global_cache.pkl deleted at exit
```

For some reason `models/dark_paradise` does not have the `artifacts` directory. Make the dir and it should work. `old_money, midnight_rain and invisible_string` are also missing these dirs and I think a few more? ModelPath gave a None because the validate flag is True and the dirs don't exist.

2024-11-04 14:49 UTC, smellycloud commented on models/dark_paradise/src/training/train_model.py
> +        stepshift_model.save(path_artifacts / model_filename)
Errors out

2024-11-04 15:03 UTC, xiaolong0728 commented on common_utils/views_stepshifter_darts/stepshifter.py
Problem fixed. I changed the template but it seemed that I didn't make the same changes to all created models.

2024-11-04 15:18 UTC, xiaolong0728 commented on models/dark_paradise/src/training/train_model.py
> +        stepshift_model.save(path_artifacts / model_filename)
I see the problem. I used the old template, so no .gitkeep is created.

2024-11-04 15:20 UTC, xiaolong0728 commented on common_utils/model_path.py
I think the problem lies in that I didn't use the template for the old models. I manually add all .gitkeep now and it should be fine.

2024-11-04 15:24 UTC, xiaolong0728 commented on models/.DS_Store
Not sure why the file exists as it is in .gitignore :( .

2024-11-05 14:32 UTC, xiaolong0728 commented on common_utils/views_stepshifter_darts/stepshifter.py
I have created a new branch to improve the stepshifter. There I'll include the switch case.

2024-11-06 10:06 UTC, smellycloud commented
Problem with invisible_string. `python main.py --train`. I'm guessing something is up with the queryset.

```
Traceback (most recent call last):
  File "/Users/user/Desktop/views_pipeline/models/invisible_string/main.py", line 35, in <module>
    execute_single_run(args)
  File "/Users/user/Desktop/views_pipeline/models/invisible_string/src/management/execute_model_runs.py", line 39, in execute_single_run
    get_data(args, config["name"], args.drift_self_test)
  File "/Users/user/Desktop/views_pipeline/models/invisible_string/src/dataloaders/get_data.py", line 11, in get_data
    data, alerts = fetch_or_load_views_df(model_name, args.run_type, path_raw, self_test, use_saved=args.saved)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/views_pipeline/common_utils/utils_dataloaders.py", line 245, in fetch_or_load_views_df
    df, alerts = get_views_df(model_name, partition, self_test, override_month)  # which is then used here
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/views_pipeline/common_utils/utils_dataloaders.py", line 202, in get_views_df
    df, alerts = fetch_data_from_viewser(model_name, month_first, month_last, drift_config_dict, self_test)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/views_pipeline/common_utils/utils_dataloaders.py", line 41, in fetch_data_from_viewser
    queryset_base = model_path.get_queryset()  # just used here..
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/views_pipeline/common_utils/model_path.py", line 485, in get_queryset
    return self._queryset.generate() if self._queryset else None
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/views_pipeline/common_querysets/queryset_invisible_string.py", line 55, in generate
    .transform.spatial.sptime_dist(distances,1,1.0,0.0)
                                   ^^^^^^^^^
NameError: name 'distances' is not defined
2024-11-06 11:02:43,314 /Users/user/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [10812] [MainThread] - INFO - Cache file: /Users/user/Desktop/views_pipeline/.global_cache.pkl deleted at exit
```

2024-11-06 10:45 UTC, smellycloud approved these changes

2024-11-13 01:58 UTC, Polichinel approved these changes
looks good to me

2024-11-13 01:58 UTC, merged