Add logging, ensemble model check, ADR
prio-data/views_pipeline pull request #47
Opened 2024-09-11 07:43 UTC by xiaolong0728

Changes in this pr:
1. Replace 'print' with logging. Prints in the utility function remain.
2. Create a utility function for ensemble model check. Conditions can be added or changed based on further discussion.
3. Add an ADR for log files
4. Move utils_wandb.py to common_utils
5. More ensemble models (old stepshift models)

2024-09-17 02:35 UTC, Polichinel requested changes
Looks good - really. there are a few notes. Some of them a for future work but a few of them are something you can address before we merge this.

:vulcan_salute:

2024-09-17 02:35 UTC, Polichinel commented on documentation/ADRs/009_log_file_for_generated_data.md
> +In the context of the VIEWS pipeline, there is a need to create a log file to ensure that models and data are tracked accurately and meet certain criteria before running.
I think we should add that these log files are used as metadata for deployment and orchestration (maybe even allude to how)

2024-09-17 02:35 UTC, Polichinel commented on documentation/ADRs/009_log_file_for_generated_data.md
> +
Yes, super. but this sense to use as an example of how it is used in the deployment

2024-09-17 02:35 UTC, Polichinel commented on documentation/ADRs/009_log_file_for_generated_data.md
> +## Consequences
Looks super

2024-09-17 02:35 UTC, Polichinel commented on documentation/ADRs/010_evaluation_metrics.md
> +| Status              | Accepted           |
Lets set this to proposed and then make a PR on the acceptance status that we invite HH, Mike and Mihai to.

2024-09-17 02:35 UTC, Polichinel commented on documentation/ADRs/010_evaluation_metrics.md
> +- **Onset Sensitivity**: The ability to detect onsets of conflict is particularly important, as these events are often of the most interest to decision-makers.
We'll need to be more specific here, but don't worry about that for now - we'll do that before we send it to review by itself

2024-09-17 02:35 UTC, Polichinel commented on ensembles/cruel_summer/src/offline_evaluation/evaluate_ensemble.py
> +    create_log_file(PATH_GENERATED_E, config, data_generation_timestamp)
Looks good

2024-09-17 02:35 UTC, Polichinel commented on ensembles/cruel_summer/src/utils/utils.py
I know I have done the same, but I think we should be more keen to have multiple well-defined utils with more clear naming. For instance utils_log_files.py, utils_configs, utils_model_output etc.

2024-09-17 02:35 UTC, Polichinel commented on ensembles/cruel_summer/src/utils/utils_check.py
Good - we have too few checks and I highly appreciate a dedicated util_check - but I think we should call it utils_checks ;) Sorry for being pedantic

2024-09-17 02:35 UTC, Polichinel commented on ensembles/white_mustang/src/utils/utils.py
same as above

2024-09-17 02:35 UTC, Polichinel commented on ensembles/white_mustang/src/utils/utils_check.py
same as above

2024-09-17 02:35 UTC, Polichinel commented on meta_tools/assess_ensemble_dir.py
good - sidenote we should also have a script like this to check all configs are ok and the queryset is valid..

2024-09-17 02:35 UTC, Polichinel commented on models/blank_space/configs/config_input_data.py
this will change but thats beside the point right now

2024-09-17 02:35 UTC, Polichinel commented on models/blank_space/src/management/execute_model_tasks.py
> -
Much better - we should have done this earlier but better late than never, right?

2024-09-17 02:35 UTC, Polichinel commented on models/blank_space/src/offline_evaluation/evaluate_model.py
I appreciate the simplification

2024-09-17 02:35 UTC, Polichinel commented on models/blank_space/src/utils/utils.py
same with the naming and more modularity

2024-09-17 02:35 UTC, Polichinel commented on models/electric_relaxation/src/utils/utils.py
Again, split the util up and give it more descriptive name

2024-09-17 02:35 UTC, Polichinel commented on models/orange_pasta/src/utils/utils.py
split and more descriptive names

2024-09-17 08:06 UTC, xiaolong0728 commented on common_utils/utils_cli_parser.py
> +    parser.add_argument('-ag', '--aggregation',
I intended to make it a choice to aggregate models by mean or median here. But it seems that we need to define the aggregation in the first place.

2024-09-17 08:37 UTC, xiaolong0728 commented on documentation/ADRs/004_generated_file_naming_convention.md
> +- run_type: The type of run (e.g., calibration, testing, forecasting).
I made a mistake. No run_type here.

2024-09-17 08:42 UTC, xiaolong0728 commented on documentation/ADRs/004_generated_file_naming_convention.md
> +
1 is prediction so the run type is forecasting (I made a mistake in the description tho) and 3 is output/evaluation so the run type is calibration or testing

2024-09-17 09:18 UTC, xiaolong0728 commented on ensembles/cruel_summer/src/utils/utils.py
I have a question: what is the difference between utils in common_utils and in src/utils. It seems that both of them are 'common'.

2024-09-17 10:00 UTC, xiaolong0728 commented on meta_tools/assess_ensemble_dir.py
The config files all include functions. How do we check them?

2024-09-17 13:19 UTC, xiaolong0728 commented on documentation/ADRs/004_generated_file_naming_convention.md
> +
So are we going to make six files?

2024-09-25 23:06 UTC, Polichinel commented on common_utils/utils_cli_parser.py
> +    parser.add_argument('-ag', '--aggregation',
noted

2024-09-25 23:08 UTC, Polichinel commented on documentation/ADRs/004_generated_file_naming_convention.md
> +- run_type: The type of run (e.g., calibration, testing, forecasting).
Noted

2024-09-25 23:08 UTC, Polichinel commented on documentation/ADRs/004_generated_file_naming_convention.md
> +
Noted - make sense

2024-09-25 23:10 UTC, Polichinel commented on ensembles/cruel_summer/src/utils/utils.py
Yeah - as we talked about the src/utils will prolly be deprecated at some point or only use for experimentations

2024-09-25 23:10 UTC, Polichinel commented on meta_tools/assess_ensemble_dir.py
Dylan is writing a thing

2024-09-25 23:11 UTC, Polichinel submitted a review, later dismissed
Looks good

2024-09-25 23:37 UTC, merged